services:

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mailhog
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    ports:
      - "8083:8083"