spring:
  application:
    name: notification

  kafka:
    bootstrap-servers: host.docker.internal:9092,host.docker.internal:9094,host.docker.internal:9096
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: in-v3.mailjet.com
    port: 587
    username: 96a787c1a75fa2f1e347e635bf17fd83
    password: 9a8821a27ba5ebbee68e7de8061a829d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true